collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.7329749
  lightness: 1
  brandColors:
    - '#92C5FA'
    - '#0B151F'
    - '#6888B1'
    - '#55342F'
    - '#FB9D6E'
  rhythmicContrast: 0.9731183
typography_spectrum: 0.1774193
layout_spectrum: 0.9426523
name: Graham Giamarino
