layout_spectrum: 0.0734767
color:
  saturation: 0.4462366
  lightness: 1
  brandStrength: 0.9247312
  brandColors:
    - '#FFFFFF'
    - '#142016'
    - '#7DAA8B'
    - '#C5DACB'
    - '#2F5B4A'
  rhythmicContrast: 0.5394265
typography_spectrum: 0.4551971
name: Graham Giamarino
