collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3243728
  brandStrength: 0.9247312
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#142016'
    - '#7DAA8B'
    - '#C5DACB'
    - '#2F5B4A'
  rhythmicContrast: 0.2616487
typography_spectrum: 0.3996416
layout_spectrum: 0
name: Graham Giamarino
